### ISSUE TITLE
MacOS M1Pro chip: Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by yuriten** [AbdBarho/stable-diffusion-webui-docker#35]
**Steps to Reproduce**
1. clone the repo 
2. copy model.ckpt to models
3. cd ./AUTOMATIC1111
5. docker compose up --build

There are no problems with the previous steps, but the last error is reported:

```sh
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 2/2
 ⠿ Network automatic1111_default    Created                                                                                                 0.0s
 ⠿ Container automatic1111-model-1  Created                                                                                                 0.1s
Attaching to automatic1111-model-1
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]
```

**Hardware / Software:**
 - MacOS 12.5 M1 Pro chip
 - GPU: No GPU

What do I need to do to fix this?

**Comment by AbdBarho** [comment]
@yuriten Mac Support is a big subject. I know that `lstein` fork [has mac support](https://github.com/lstein/stable-diffusion/blob/main/README-Mac-MPS.md), but I cannot integrate it because I don't have a mac.

If you would like to contibute and implement it I will gladly add it to the repo.

related #31

**Comment by jasalt** [comment]
There's also SD in app format for Mac (Apple Silicon) now: https://github.com/divamgupta/diffusionbee-stable-diffusion-ui. Probably easiest way to get SD running there while the Docker ARM support is lagging behind.

**Comment by AdamGoyer** [comment]
gm,
Checking in briefly. Has any progress been made on Apple M1 Silicon since Sept 2022?

**Comment by jasalt** [comment]
@AdamGoyer Running the AUTOMATIC1111 UI without Docker following [the wiki docs](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Installation-on-Apple-Silicon) has been easiest and most feature rich way to run SD Web UI on ARM Mac as far as I know. Works quite fine with 16GB ram model at least.

**Comment by AdamGoyer** [comment]
- -

**Comment by jasalt** [comment]
@AdamGoyer Haha, nice. It would be cool for sure but I wonder if it's even possible without Docker adding GPU passthrough like WSL2 which only Parallels and virgl seem to be able to do it to some extent (ref https://apple.stackexchange.com/a/453103/29042). Or maybe use some tricks to use the PyTorch etc. from Mac side..

Personally tried migrating web dev setup from AMD64 Intel Mac to ARM Apple Silicon but got fed up as features and docs seemed lagging behind on many fronts and clients weren't paying for resolving multi-architecture issues either.

**Comment by Ntsako-Hlungwani** [comment]
Docker Compose Configuration:
Check your Docker Compose configuration to make sure that you have specified the correct runtime and options for NVIDIA GPUs. Here is an example snippet you might include in your docker-compose.yml file:
services:
  automatic1111-model-1:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # ... other configurations ...

**Comment by cmutnik** [comment]
@jasalt I made a docker image that spinds up locally (mac m3) and launches the `AUTOMATIC1111/stable-diffusion-webui` through `localhost:7860`

I got it to work using the vscode method from [think link](https://gist.github.com/BillRaymond/74b82f703239480518af1fa67a240d96) but that only worked in vscode cuz gradio is so fun.  So I hacked together an image you can build and run locally, without requiring vscode; just needs the simple commands:
```sh
docker build -t sdwebui:lite -f Dockerfile .
docker run -it -p 7860:7860 sdwebui:lite
```

This has been tested and works, but the Dockerfile is a mess haha.  Deff not something good enough to submit for a PR yet.  Whenever I have the time Ill clean it up and put in a PR, or anyone else who wants to make it prettier/remove duplicate logic can.  Until then, Im currently in the process of pushing it to docker hub:
```
docker image tag sdwebui:lite letsstartdocking/sdwebui:lightonmodels
docker push letsstartdocking/sdwebui:lightonmodels
```

All this to say -- its possible, I have the code; just need to find the time so a PR isn't embarrassingly ugly haha.

![sd_webui_mac_m1](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/13492050/ae24668a-4c4c-4395-ac98-120d3310948e)

**Comment by cmutnik** [comment]
anyone who wants access to the really bad dockerfile can have it (just no shaming until its cleaned up haha)

**Comment by cmutnik** [comment]
[PR is open](https://github.com/AbdBarho/stable-diffusion-webui-docker/pull/677), please see notes/comments for discussion.

**Comment by MatchlessHeroVIP** [comment]
mac boookpro M1 芯片build报错 could not select device driver "nvidia" with capabilities: [[compute utility]]

**Comment by cmutnik** [comment]
Is there a way to emulate an m1 chip so I can troubleshoot that for you?

**Comment by ziqq** [comment]
@MatchlessHeroVIP, i have this same issue.
```console
Attaching to auto-1
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: could not select devi
```

**Comment by ziqq** [comment]
Hi @cmutnik
<details>
  <summary>Emulate M1</summary>

  #### Emulating the Apple M1 chip is a challenging task because the M1 is based on the ARM architecture, and accurately emulating it requires specialized software and significant computational resources.
  
  #### Available Options:
  QEMU with ARM support: QEMU is a popular emulator that supports ARM emulation. However, emulating the M1 through QEMU requires deep technical knowledge and significant configuration, and even then, the performance will be far from what you’d get on an actual M1 device.
  
  #### UTM: 
UTM is a tool based on QEMU that offers a more user-friendly interface for ARM emulation on Apple devices. UTM supports the emulation of various architectures, including ARM, and could theoretically be used to emulate M1-based devices, though, again, the performance and accuracy will be limited.
  
  #### Rosetta 2: 
If the goal is to run applications developed for Intel on M1 devices, Apple provides Rosetta 2, which allows for this. This is not emulation but rather instruction translation, which can help developers test for compatibility.
  
  #### Why Emulating M1 is Difficult:
  The Apple M1 is a system on a chip (SoC) with highly integrated components, including the CPU, GPU, neural engine, and specialized modules for security and memory. Emulating all these components accurately is extremely complex and requires specialized hardware and software.
  
  #### Alternatives:
  If you need to test applications intended to run on the M1, the best option is to use actual devices with this chip or virtual machines supported by Apple, such as virtual devices in Xcode on a Mac with an M1 chip.
  
  #### In summary, there is no full-fledged emulation of the M1 chip currently available, but some tools can assist in specific scenarios.
</details>

**Comment by cmutnik** [comment]
Thanks @ziqq I am on an M3 which is also arm arch, so I was hoping of a way to emulate whatever the differences are between M1 and M2/M3 that allow all of this to work on M2/M3 but now on M1
